name: opaque
description: >-
  Dart bindings to libopaque
version: 1.0.0
environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  test: ">=1.15.0 <2.0.0"
  build_runner: ">=1.6.2 <3.0.0"
  build_web_compilers: ">=2.12.0 <4.0.0"

dependencies:
  ffi: ^1.1.2
  sodium: ^1.2.0+2
